const employmentData = [
  {
    name: "Founder, Tiffany Lea LLC",
    location: "West Hollywood, CA",
    duration: "3/18 — current",
    details: [
      "Web development, consulting services, and contract work using the newest technologies",
    ],
    techUsed: [
      "Typescript",
      "React",
      "React Hooks",
      "Next.js",
      "GraphQL",
      "Apollo",
      "Storybook",
      "NPM",
      "Github",
      "AWS",
      "Amplify",
      "Cloud Formation",
      "AppSync",
      "Cloud Watch",
      "S3",
      "Route53",
      "DynamoDB",
      "Cognito",
      "Android",
      "iOS",
      " CI/CD",
      "Figma",
      "Jest",
      "SCSS",
      "Google Lighthouse",
      "NPM",
      "Ionic",
      "SSR",
    ],
  },
  {
    name: "Quantum Metric",
    location: "Colorado Springs, CO (Remote)",
    duration: "2/21 — 3/23 (2 years 1 month)",
    techUsed: [
      "Typescript",
      "React",
      "MobX",
      "D3",
      "Storybook",
      "Figma",
      "GraphQL",
      "SCSS",
      "Docker",
      "Docusaurus",
      "GitLab",
      "CI/CD",
      "NPM",
      "Figma API",
      "Jest",
      "Rollup",
      "Testing Library",
      "Accessibility",
      "Automation",
      "Design Systems",
      "Documentation",
      "ADRs",
      "SSG",
    ],
    roles: [
      {
        duration: "1 year",
        title: "Staff Software Engineer",
        summary:
          "Worked across teams and departments to create the foundations for Margarita Design System:",
        details: [
          "Worked with the User Experience Research team to survey engineers about the current ecosystem and pain points",
          "Planned and executed solutions for processes, documentation, communication, component explorer, design guidelines, component library, Figma integration, automation, developer experience, and more...",
          "Built accessible, extensible, testable, and reusable components for use by engineers",
          "Shared progress and maintained a feedback loop with the engineering department",
        ],
      },
      {
        duration: "1 year",
        title: "Senior Software Engineer",
        details: [
          "Created and maintained  Storybook, including documentation to help align vocabulary, architecture, and thought process",
          "Worked across engineering, product, and design to define a design system roadmap",
          "Contributed to many teams/features, including replay, live replay, dashboards and sandbox",
          "Participated in hiring, ongoing documentation, defining code standards, and more",
        ],
      },
    ],
  },
  {
    name: "Endpoint Closing",
    location: "El Segundo, CA",
    duration: "3/18 — 7/19 (1 year 6 months)",
    techUsed: [
      "React",
      "React Native",
      "Redux",
      "Reselect",
      "Jest",
      "NPM",
      "Jira",
      "Webpack",
      "Rollup.js",
      "Babel",
      "ESLint",
      "Responsive Web Design (RWD)",
      "Gitlab CI",
      "AWS",
      "DynamoDB",
      "Lambda",
    ],
    roles: [
      {
        title: "Lead of Front End Engineering",
        duration: "1 year",
        details: [
          "Directed the design team in adapting a more component-based process and mindset",
          "Facilitated the creation of a universal component library to support reuse between multiple applications and platforms",
          "Assisted in the planning and implementation of the first iteration of website analytics",
          "Company-wide UX lunch and learn, focused on usability and accessibility",
        ],
      },
      {
        title: "Senior JavaScript Engineer, BCG Digital Ventures",
        duration: "6 months",
        details: [
          "Contract work during incubation and initial development phase of Endpoint Closing",
          "Assisted in developing both web and native applications from inception to production",
          "Architected a smart-form builder that dynamically generates forms based on JSON schemas for the entire closing process, including digital signatures and money transfers",
        ],
      },
    ],
  },
  {
    name: "SKECHERS USA, Inc.",
    location: "Manhattan Beach, CA",
    duration: "6/14 — 3/18 (3 years 10 months)",
    techUsed: [
      "Backbone",
      "Marionette",
      "CoffeeScript",
      "Handlebars",
      "Zepto",
      "Angular",
      "RequireJS",
      "Jasmine",
      "Karma",
      "Squire",
      "Sinon",
      "CasperJS",
      "Sass",
      "Bootstrap",
      "HTML5",
      "CSS3",
      "React",
      "Redux",
      "Scala",
      "Blackbaud",
      "Constant Contact",
      "Google Tag Manager",
      "Jekyll",
      "Jenkins",
      "CI/CD",
      "Automation",
    ],
    roles: [
      {
        title: "Manager of Front End Engineering",
        duration: "1 year",
        details: [
          "5-6 Direct reports, reported directly to the VP of the Digital Department for all things frontend",
          "Integrated a custom Data Layer into Google Tag Manager to provide enhanced analytics for multiple vendors",
          "AI chatbot to assist shoppers in finding the perfect shoes based on 3 selections",
          "Responsible for architecture and execution of frontend solutions for multiple high-traffic sites",
        ],
      },
      {
        title: "Senior Javascript Engineer",
        duration: "10 months",
        details: [
          "Rewrote Skechers Direct (B2B solution used within companies like Starbucks and Taco Bell), including a separate admin site to manage products, discounts, site content/features and orders for each company",
          "Collaborated across departments and vendors regarding responsive solutions, UI/UX, analytics, and A/B testing of multiple websites",
        ],
      },
      {
        title: "Javascript Engineer",
        duration: "1 year",
        details: [
          "Extended skechers.com to multiple locales by adding functionality, payment processors, and other locale-specific features",
          "Per locale settings, language and feature toggles could be adjusted via the admin portal",
          "SKECHERS corporate site",
        ],
      },
      {
        title: "Frontend Developer",
        duration: "1 year",
        details: [
          "Implemented responsive solutions for existing websites",
          "Managed SkechersFriendshipWalk.com and assisted in any technical needs (registration, email campaigns, analytics, system admin)",
          "Joined the team in rewriting Skechers.com from the ground up, including an admin site for product, order, and site management",
        ],
      },
    ],
  },
  {
    name: "Lead Web Developer, Beacon Technologies",
    location: "Greensboro, NC",
    duration: "11/09 — 6/14 (4 years 8 months)",
    techUsed: [
      "Cascade Server",
      "AspDotNetStorefront",
      "Drupal",
      "WordPress",
      "phpBB",
      "Magento",
      "PHP",
      "XML",
      "XSLT",
      "Velocity",
      "HTML",
      "CSS",
      "Javascript",
      "jQuery",
      "W3C",
      "508",
      "Responsive Web Design",
      "Software Development Life Cycle (SDLC)",
      "Google Analytics",
      "UX",
      "Accessibility",
      "Usability",
      "Cross-browser Compatibility",
      "E-commerce",
      "Higher-ed",
      "Information Architecture (IA)",
      "Intranets",
    ],
    details: [
      "Involved in all aspects and phases of the project lifecycle from proposals to launch",
      "Mentor and train team members with continuous documentation of standards, best practices, and processes",
      "65 + Projects across multiple technologies and industries, including e-commerce, universities, complex CMS integrations, intranets",
    ],
  },
  {
    name: "Web Developer, Get You Found Online Marketing",
    location: "Greensboro, NC",
    duration: "11/08 — 12/09 (1 year 2 months)",
    techUsed: [
      "PHP",
      "SQL",
      "RDMS",
      "MySql",
      "phpMyAdmin",
      "Drupal",
      "Magento",
      "WordPress",
      "Joomla",
      "HTML",
      "CSS",
      "Javascript",
      "W3C",
      "Advanced CMS Setup and Configuration",
      "E-commerce ",
    ],
    details: [
      "Contracted to design and develop medium to large-scale websites for clients",
      "Involved in all aspects and phases of the project lifecycle",
      "10+ Custom CMS integrations, including theming, configuring, and customizing Drupal and Magento based websites",
    ],
  },
  {
    name: "Web Developer, Inter-Tech Communications - CarolinaNet",
    location: "Greensboro, NC",
    duration: "9/07 — 2/09 (1 year 6 months)",
    techUsed: [
      "PHP",
      "Classic ASP",
      "SQL",
      "RDMS",
      "MySql",
      "phpMyAdmin",
      "Domain Registrar",
      "DNS",
      "Virtual Private Servers (VPS)",
      "Virtuozzo",
      "Plesk",
      "Plesk Business Automation",
      "Joomla",
      "ZenCart",
      "Drupal",
      "Design",
      "HTML",
      "CSS",
      "Javascript",
      "W3C",
      "SEO",
      "Google Analytics",
      "Autotask",
      "Advanced CMS Configuration",
      "E-commerce",
      "Adobe Creative Suite",
    ],
    details: [
      "Blackberry server management, migration to Plesk Business Automation, multiple weekly e-newsletters, second-level IT support",
      "35+ Micro-sites, which included domain, DNS, website, and email setup and configuration",
      "20+ Projects, including small to medium-sized business sites and custom MySpace",
    ],
  },
];

export default employmentData;
